spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: rg.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true

